#!/usr/bin/with-contenv bash

cd /usr/lib/unifi-video || exit

exec s6-setuidgid unifi-video java \
    -cp /usr/share/java/commons-daemon.jar:/usr/lib/unifi-video/lib/airvision.jar \
    -Djava.security.egd=file:/dev/./urandom \
    -Djava.library.path=/usr/lib/unifi-video/lib \
    -Djava.awt.headless=true \
    -Djavax.net.ssl.trustStore=/usr/lib/unifi-video/data/ufv-truststore \
    -Dfile.encoding=UTF-8 \
    com.ubnt.airvision.Main start
