#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/{data,logs,run}

# create symlinks for config
[[ -L /usr/lib/unifi-video/data && ! /usr/lib/unifi-video/data -ef /config/data ]] && unlink /usr/lib/unifi-video/data
[[ -L /usr/lib/unifi-video/logs && ! /usr/lib/unifi-video/logs -ef /config/logs ]] && unlink /usr/lib/unifi-video/logs
[[ -L /usr/lib/unifi-video/run && ! /usr/lib/unifi-video/run -ef /config/run ]] && unlink /usr/lib/unifi-video/run
[[ ! -L /usr/lib/unifi-video/data ]] && ln -s /config/data /usr/lib/unifi-video/data
[[ ! -L /usr/lib/unifi-video/logs ]] && ln -s /config/logs /usr/lib/unifi-video/logs
[[ ! -L /usr/lib/unifi-video/run ]] && ln -s /config/run /usr/lib/unifi-video/run

# start the wizard if no existing config is present
[[ ! -f /config/data/system.properties ]] && echo "is_default=true" >> /config/data/system.properties

# permissions
chown -R unifi-video:unifi-video /config
